### ISSUE TITLE
Allow to change attributes for marks in a convenient way

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#1]
Unknown marks use for comparison only string patterns and do not consider rules. Only during creation you can use attributes. Moreover, you can just choose only equality of attributes, and you can not forbid to apply this mark to some values, i.e. check the attribute for inequality.

**Comment by vmordan** [comment]
Which possibilities are required for creation/edition of Unknown marks except checking the attribute for inequality?

**Comment by vmordan** [comment]
I think, this issue can be reformulated in the following way: extend marks (not only Unknowns) application by attributes. Currently, we can only apply mark, if report contain specific attribute with specific value.
Potential extension are:
- check for inequality (e.g., apply for all rules, except races);
- check for greater/lesser/etc. (e.g., apply if number of found error traces is greater, than 1);
- support regexps (e.g., apply for "sync:*" rules).

Would such extensions be useful?

**Comment by PavelAndrianov** [comment]
I think yes, but it also leads to more complicated mark interface. It is already not very simple and we may not remember about all it possibilities even now.

**Comment by vmordan** [comment]
Currently attributes can be changed only on extended marks creation/edition, which is supposed to be more complicated. In order to help new users understand it, such features should be documented (#10).

**Comment by PavelAndrianov** [comment]
Yes, extended creation have to be more complicated, but seems, we are approaching "overcomplication", when even experts may not remember about all the available options. So, the good idea will be to reorginize the extended creation page. Because a bit more "a bit more options" may confuse all experts.

**Comment by vmordan** [comment]
Resolved in commit 04fb2b98
