### ISSUE TITLE
Add documentation on pages

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#10]
Currently there is no good documentation, which describes each page and its purpose.
At the same time this documentation will be needed for new users to understand verification results.

**Comment by PavelAndrianov** [comment]
I am not completely understand, what pages do you mean?

**Comment by vmordan** [comment]
Basic pages:
1. Main (reports tree)
2. Report detailed description
3. Creation of marks
etc.

It would be good to describe some basic functionality, for example, how to compare reports or how to create/change extended mark.

**Comment by PavelAndrianov** [comment]
OK, web-pages, I see.

**Comment by vmordan** [comment]
I suggest to create a special "help" page for each nontrivial web-page (such as, extended marks creation or reports comparison settings) with the short description of main use cases. 
This can be helpful for new users.

**Comment by PavelAndrianov** [comment]
It would be good to look at some brief overview of such page. How it may look like? Just web version of readme or anything else?

**Comment by vmordan** [comment]
Documentation for the main pages was added in commits 49de6d5e...715e1a0b.
