### ISSUE TITLE
Extend comparison function parameters

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#11]
Now the parameter can be presented only with normal funciton calls. In some cases we need to add an expression or an undefined function call.

**Comment by vmordan** [comment]
Which parameters are also required?
For example, function arguments for both 'model functions' and 'call tree'?

**Comment by PavelAndrianov** [comment]
I could not enumerate all necessary parameters. Right now, I faced with undefined functions. We may start from this case and add something else iteratively.

**Comment by vmordan** [comment]
Commit 34b7f1d added a few extensions to the comparison function parameters.
Do we need to support any other parameter?

**Comment by vmordan** [comment]
List of supported conversion function arguments:

1. Additional model functions (for `model functions` conversion function).
2. Ignored function calls.
3. Adding/removing notes/warnings full description/location only.
