### ISSUE TITLE
Unify coloring schema

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#12]
Colors for the following elements should be unified:
1. Main background (all colored tables).
2. Unsafe verdicts: Bug, False alarm, Unknown, Incompatible, no marks.
3. Marks statuses: Unreported, Reported, Fixed, Rejected.
4. Safe verdicts (not important).

**Comment by vmordan** [comment]
This should take into account, that some verdicts will be shown on colored background.

**Comment by vmordan** [comment]
My suggestion:
1. light-blue (#cafdff)
2. Red, orange, purple, purple, black.
3. Red, dark-blue(?), green, orange.

**Comment by vmordan** [comment]
Implemented in fb6da17

**Comment by PavelAndrianov** [comment]
Seems, not related to this particular issue, but there are still questions about colours in visualization of true witnesses. There are two similar green colours, which mean different things. We have to deal with it, because on some monitors or options (brightness) there are no differences.

**Comment by vmordan** [comment]
I think correctness witnesses visualization may be changed and thus this problem will be resolved as well. For example, we can separate views (covered/uncovered conditions, covered/uncovered lines).
