### ISSUE TITLE
Workout a way to make references to the error trace in the description easily

### ISSUE THREAD

**Issue by mutilin** [mutilin/klever#18]
Now you have to copy paste the code from the source and adjust it into description.
It would be nice to make references to the source easily, e.g. by putting only line number (and it automatically substitutes by source text) or by clicking on the line to be pasted into description. We should think about it

**Comment by vmordan** [comment]
Only line number would be insufficient, because there are also different files (and sometimes the same line number leads to different files).

**Comment by PavelAndrianov** [comment]
Just an idea. There may be useful to insert some comments into the error trace itself. Like coverity-style. So, the mark contains a map "function in converted trace -> description" and this description is shown near (before, after or on the right) the model function on the full trace. So, you should not read a description below the trace, you have just follow the described points in the error trace itself.

**Comment by vmordan** [comment]
Commit 6043096 added support for appending source code to the mark description by clicking on the line number. This works only for light-weighted mark creation, since only this view contains actual error trace (therefore, it is not supported on the extended mark creation/edition page).
