### ISSUE TITLE
Problems with error trace conversion

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#19]
- [x]  Strange behaviour with indentations in case of partial include.
```
...
|    __ERROR__
| function1
| function2
```
is replaced (after "save" button") into 
```
...
|    __ERROR__
| function1
|  function2
```
So, the space is added, this changes semantics of an error trace. Note, the only first level of function calls is changed.
- [x]  Strange behaviour with indentations in case of normal include. The second trace totally miss all indentations:
```
...
|    __ERROR__
| function1
|  function2
|   function3
```
is replaced into 
```
...
|    __ERROR__
| function1
| function2
| function3
```

**Comment by vmordan** [comment]
Fixed bugs, which caused these problems.
