### ISSUE TITLE
Copying attributes from unsafe page

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#22]
After improvement, which allows to click to any place on a row to choose an error trace, that is impossible to copy attribute without entering the next page. So, if I just want to copy an attribute at unsafes list page, I select a text, but after that I am redirected to error trace page. In the worst case (fast server and net speed) I may even have no time to push ctrl + c. Anyway I can copy the attribute on this page, nevertheless it is inconvenient.

**Comment by vmordan** [comment]
It is possible to remove links from the whole rows, but it would be less convenient to redirect to the error trace page. Alternatively links can be removed from attributes columns.

**Comment by PavelAndrianov** [comment]
I do not consider, that we should remove whole links and so return to the old (origin) Klever. The links are very convenient. But I do not know any good solution for this problem, so it is a low priority unless someone suggest a good solution.

**Comment by vmordan** [comment]
Improvement to those lists visualization were implemented in commit 139c675.

**Comment by vmordan** [comment]
Unified links styles for these lists in 0f16de1.
