### ISSUE TITLE
Automatic system for creating backups

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#27]
All marks and tags should be saved somewhere automatically to prevent data loss.

**Comment by vmordan** [comment]
Commit 9b9b652 adds manager action for saving tags.

**Comment by PavelAndrianov** [comment]
It is better to have an ability for automatic dump.

**Comment by vmordan** [comment]
Added in commit af61aa7.
It is possible to specify a directory and interval for automatic backups or disable this feature.
By default it creates backups every day.

**Comment by PavelAndrianov** [comment]
Just to think about. Could we dump only after changes? So, I think there will be days, where the marks will not be added.

**Comment by vmordan** [comment]
Commit 6326402 added check for changes before creating a backup.
At the same time creating backups is performed only once per day (can be changed in settings), therefore a lot of small changes in marks during the same day will not lead to many useless copies.
