### ISSUE TITLE
Mode to display all nested notes

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#30]
Now all nested nodes are hidden. It is useful for ordinary rules, as the internal structure of model function is not displayed for all users. If you need it, you may open it by yourself.
Anyway special rules, like races and smg, usually set notes for a specific operators, which are relevant for error. For example, sometimes we may not find a necessary lock due to it was hidden by an overlaying note. The same is for smg, which may set a note for a function and a return value from it. An idea is to have an option to show all hidden notes. It should be disabled by default, but the option to see all notes may be useful for an expert.

**Comment by vmordan** [comment]
Several modes to display error trace were implemented in commit 265c25c.
