### ISSUE TITLE
Specify Unknown transitions in the reports comparison page 

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#32]
Currently there is no information in the reports comparison page about Unknowns with different problems. Such information can be useful, for example, transitions from time limit to some exception. This can be implemented similar to error trace clustering for Unsafe verdicts.

**Comment by PavelAndrianov** [comment]
Support this. There are minor questions, if it should be enabled by default or not and how the clusters are calculated. So, for unsafes there are clusters based either on marks or on converted error traces. What identifier will be used for unknown if there is no mark?

**Comment by vmordan** [comment]
It can be disable by default (similar to Unsafes).
I don't think there should be clustering (distribution of unknown verdicts by problems), because this information is shown on the job page. Instead we can compare problems for each Unknown and show only different (can be change in settings). For example:

Timelimit - attrs1 - Assertion
Timelimit - attrs2 - No marks

**Comment by PavelAndrianov** [comment]
Thus we may hide a problem. So, No marks -> No marks in not shown as equal, but the problems are different and user may miss it. Nevertheless, I agree, that now user misses much more information, so this case will be useful.

**Comment by vmordan** [comment]
Implemented in 3c27b62
