### ISSUE TITLE
Show coverage for reports

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#35]
Coverage data currently can be loaded only as number (in %), but Klever can display full coverage for reports. We should either support it, or re-implement it.

**Comment by PavelAndrianov** [comment]
Before complete support/reimplementation we should discuss, how it can be improved. For example, Klever shows covered lines with red. User expects, that red colour means "uncovered". It is a small unconvenience, but I guess, there may be some more, if we look deep into implementation.

**Comment by vmordan** [comment]
After the first look at the current implementation of coverage in Klever I found the following potential problems:
* Each archive with coverage contains all required source files, which is a huge waste of space. For example, if we have 5 properties and 100 entry points, then this method saves the same (mostly) files 500 times. Original Klever has similar problem with source files for error traces (duplicated sources), but the number of coverage reports usually bigger and thus problem is even more important. Thus original Klever report archive may contain similar source files for both error traces and coverage reports.
* Functionality for creating coverage reports requires a lot of Klever internal arguments, which makes it more harder to use outside of Klever.

Thus it would be better to reimplement or completely rewrite this feature for CV.

**Comment by vmordan** [comment]
Commits 4904ce8...f70ea2e allows to use core coverage module outside of Klever.
Commits f70ea2e...55a138f rewrites representation of coverage. The main features are the following:
- by default only function declaration is shown for each file (this is required to process huge files);
- function bodies can be shown if needed (to see line coverage);
- files paths are pruned;
- redesigned the whole page;
- changed coloring schema for most objects;
- removed some unused data from the page;
- removed useless for the users button (there is not need to save internal representation of coverage, if it cannot be used outside or even loaded);
- prevented failing on non-exited files (this is common situation during applying changes or missing files, when coverage is not displayed at all).

**Comment by vmordan** [comment]
Since coverage can be shown, this issue is closed.
