### ISSUE TITLE
Restore support for Klever core

### ISSUE THREAD

**Issue by vmordan** [mutilin/klever#42]
Currently CV cannot "launch" jobs as Klever, but still Klever can be launched via command line.
Such support should be restored in order to use CV for creating tasks via Klever core (e.g., to verify Linux kernel modules).

**Comment by PavelAndrianov** [comment]
I would say, that it is not very priority feature, because Klever changes rapidly and the effort for merging its functionality into CV is very hard. Thus, we may loose a lot of time and after that the Klever changes its interface again. Anyway, it is useful to think about merging.

**Comment by vmordan** [comment]
After performing some investigations, I found out, that this feature will require too much effort. There are a lot of problems:

* this version of Klever requires, that all system under verification were uploaded into the database, which was intentionally removed from CV (those source files are duplicated enough in Klever);
* there are no actual command line interface (it simply sends exactly the same query as corresponding "Start" button), therefore it is impossible to run it outside of web-interface (i.e., prepare resulting archive and then upload it);
* the whole installation process is even more confusing than before (and thus it would be impossible to do it for new users);
* verifier cloud interface is not supported in a way CV uses it (so we can launch modified verifier versions);
* and more.

Thus supporting Klever in CV may require to rewrite half of the Klever itself.
