### ISSUE TITLE
Adjustment of views via attributes

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#5]
Now a user can choose view for all unsafe tables, but all attributes can be enabled or disabled at once. I can not hide or show only one of attribute, say, declaration.

**Comment by vmordan** [comment]
This should be done for all pages, which include lists of Safe/Unsafe/Unknown reports.

**Comment by vmordan** [comment]
Implemented for lists of Safe/Unsafe/Unknown reports in commit 0283912

**Comment by vmordan** [comment]
Implemented for lists on marks pages in commit 6183a4d
