### ISSUE TITLE
Reuse benchexec statistics

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#50]
It may be useful to have some general summary, as benchexec does. For instance, graphics may be a part of some report. So, the main task is to join all different csv output from several benchexec launches, and then generate an html statistics. One of the problem may be related with the same file names, which are launched with different configurations.
An extension is a possibility to join and compare different jobs.

**Comment by vmordan** [comment]
CV job statistics is rather different and most likely should not fully copy it from BenchExec. At the same time, some statistics can be exported.
I think, the following statistics from BenchExec can be useful for CV:

- verifier tool options (they can be obtained from log but only for Unknowns), maybe even full job config;
- resource limitations;
- more resources (energy, blkio-w, etc.);
- quantile plot on the job page;
- scatter plot on the comparison page.

Statistics, which probably is not required in CV:
- score;
- hosts (this may be relevant, if hosts have different CPU);
- source files (they are partially shown for coverage and error traces);
- logs for safes/unsafes (too much space);
- giant comparison tables (there is a comparison page).

**Comment by PavelAndrianov** [comment]
Not quite sure, why we need statistics about energy. The rest looks reasonable.

**Comment by vmordan** [comment]
The point is to extend hard-coded resources (currently cpu time, wall time, memory), so it would be easy to add any new value. Column 'energy' I specified only as an example, since it presented in the last SV-COMP.

**Comment by vmordan** [comment]
Commit 6eea988 adds support for quantile plots on the job page and on the comparison pages (for multiple jobs).

**Comment by vmordan** [comment]
Commit f85ee4d adds support for scatter plots on the comparison page.

**Comment by vmordan** [comment]
Commit d62071f adds support for any new verification resources. They should be specified in the verification reports.

**Comment by vmordan** [comment]
Commit 585c002 adds support for verification configuration (such as resource limitation, tool options, etc.).
