### ISSUE TITLE
Description is not clear

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#6]
The description of comparison criteria "First converted trace is included into the second" is not clear. What is the first and the second ones?

**Comment by vmordan** [comment]
Improved description in commit 6c1cd55.
The main idea is to name 'first' trace 'edited' (by user actions or conversion function) and 'second' trace 'compared'.

**Comment by vmordan** [comment]
Translation of description still need to be fixed.

**Comment by vmordan** [comment]
Fixed
