### ISSUE TITLE
Problem with witnesses without relative paths

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#60]
With a new benchexec all witnesses contain a link to an origin sources like './cil.i', as the path was get from yml files, which are usually close to a cil file. Thus, the visualization does not work, as it uses simlinks. An [example](https://github.com/mutilin/klever/files/4060200/archive.zip) attached (note, there is one manually changed witness).

**Comment by vmordan** [comment]
Fixed in commit 91c3730.
