### ISSUE TITLE
Show some progress while applying a mark

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#7]
If there is a lot of similar unsafes (with equal attributes), applying a mark takes a lot of time. A user should be somehow notified, that the process is not stagnated.

**Comment by vmordan** [comment]
Commit fdda96e8 adds a workaround, which allows to apply marks only to current reports traces (is not set by default).
More thorough resolution should be done together with #7.

**Comment by vmordan** [comment]
Implemented in 670e0e9
