### ISSUE TITLE
Optimize application of marks

### ISSUE THREAD

**Issue by PavelAndrianov** [mutilin/klever#8]
Application of marks takes too long time. It should be optimized. 

- [x] The first idea is to limit application with current job. So, immediate results should be provided only for the current job, the other ones may be postponed for a convenient case. 

- [ ] The second idea is to apply marks during conversion. For example, if the first function in error trace call differs from the mark one, we have no need to calculate the whole trace.

**Comment by vmordan** [comment]
Commit fdda96e8 adds a workaround, which allows to apply marks only to current reports traces (is not set by default).
More thorough resolution should be done together with #7.

**Comment by vmordan** [comment]
The second sub-task is rather work-around, because if we skip for some reason creating of converted error trace, it still should be done later.
Optimization of marks application will be done in #20.
